#!/usr/bin/env python3

import rclpy
from rclpy.node import Node

from sensor_msgs.msg import Joy
from ackermann_msgs.msg import AckermannDrive


class DDTTeleop(Node):
    def __init__(self):
        super().__init__("leo2_teleop", start_parameter_services=False)

        self.retrieve_parameters()

        self.cmd_pub = self.create_publisher(
            AckermannDrive, "cmd_ackermann", 10
        )
        self.joy_sub = self.create_subscription(Joy, "joy", self.joy_callback, 10)

    def retrieve_parameters(self):
        self.declare_parameter("axis_speed", 1)
        self.declare_parameter("axis_steer", 3)
        self.declare_parameter("button_deadman", 5)
        self.declare_parameter("scale_speed", 1.0)
        self.declare_parameter("scale_steer", 1.1)

        self.axis_speed = (
            self.get_parameter("axis_speed").get_parameter_value().integer_value
        )
        self.axis_steer = (
            self.get_parameter("axis_steer").get_parameter_value().integer_value
        )
        self.button_deadman = (
            self.get_parameter("button_deadman").get_parameter_value().integer_value
        )
        self.scale_speed = (
            self.get_parameter("scale_speed").get_parameter_value().double_value
        )
        self.scale_steer = (
            self.get_parameter("scale_steer").get_parameter_value().double_value
        )

    def joy_callback(self, data: Joy):
        print(data)
        cmd = AckermannDrive()
        cmd.acceleration = 2.0
        cmd.steering_angle_velocity = 2.0

        if data.buttons[self.button_deadman] == 1:
            cmd.speed = data.axes[self.axis_speed] * self.scale_speed
            cmd.steering_angle = data.axes[self.axis_steer] * self.scale_steer
        else:
            cmd.speed = 0.0
            cmd.steering_angle = 0.0

        self.cmd_pub.publish(cmd)


def main():
    rclpy.init()
    node = DDTTeleop()
    rclpy.spin(node)


if __name__ == "__main__":
    main()
