#!/usr/bin/env python3

import rclpy
from rclpy.node import Node

from sensor_msgs.msg import Joy
from ackermann_msgs.msg import AckermannDrive
from rapha_interfaces.srv import SetSteeringMode
from rapha_interfaces.msg import SteeringMode


class RaphaTeleop(Node):
    def __init__(self):
        super().__init__("rapha_teleop", start_parameter_services=False)

        self.retrieve_parameters()

        self.set_steering_mode_client = self.create_client(
            SetSteeringMode, "controller/set_steering_mode"
        )
        while not self.set_steering_mode_client.wait_for_service(timeout_sec=1.0):
            self.get_logger().info(
                "controller/set_steering_mode service not available, waiting again..."
            )

        # turning in place mode arbitralily starts as false TODO - change this
        self.current_steering_mode: int = SteeringMode.ACKERMANN
        self.target_steering_mode: int = SteeringMode.ACKERMANN
        self.is_changing_mode = False

        self.cmd_pub = self.create_publisher(
            AckermannDrive, "controller/cmd_ackermann", 10
        )
        self.joy_sub = self.create_subscription(Joy, "joy", self.joy_callback, 10)

    def retrieve_parameters(self):
        self.declare_parameter("axis_speed", 1)
        self.declare_parameter("axis_steer", 3)
        self.declare_parameter("button_deadman", 5)
        self.declare_parameter("button_change_steering_mode", 1)
        self.declare_parameter("scale_speed", 1.0)
        self.declare_parameter("scale_steer", 1.1)

        self.axis_speed = (
            self.get_parameter("axis_speed").get_parameter_value().integer_value
        )
        self.axis_steer = (
            self.get_parameter("axis_steer").get_parameter_value().integer_value
        )
        self.button_deadman = (
            self.get_parameter("button_deadman").get_parameter_value().integer_value
        )
        self.button_change_steering_mode = (
            self.get_parameter("button_change_steering_mode")
            .get_parameter_value()
            .integer_value
        )
        self.scale_speed = (
            self.get_parameter("scale_speed").get_parameter_value().double_value
        )
        self.scale_steer = (
            self.get_parameter("scale_steer").get_parameter_value().double_value
        )

    def set_steering_mode_done_callback(self, future):
        if not future.result().success:
            self.get_logger().info("Failed to change steering mode")
        else:
            self.get_logger().info("Steering mode changed")
            self.current_steering_mode = self.target_steering_mode
        self.is_changing_mode = False

    def change_steering_mode(self):
        if self.is_changing_mode:
            return

        if self.current_steering_mode == SteeringMode.TURN_IN_PLACE:
            self.target_steering_mode = SteeringMode.ACKERMANN
        else:
            self.target_steering_mode = SteeringMode.TURN_IN_PLACE

        req = SetSteeringMode.Request()
        req.steering_mode.data = self.target_steering_mode
        self.is_changing_mode = True

        future = self.set_steering_mode_client.call_async(req)

        future.add_done_callback(self.set_steering_mode_done_callback)

    def joy_callback(self, data: Joy):
        cmd = AckermannDrive()
        cmd.acceleration = 2.0
        cmd.steering_angle_velocity = 2.0

        if data.buttons[self.button_deadman] == 1:
            cmd.speed = data.axes[self.axis_speed] * self.scale_speed
            cmd.steering_angle = data.axes[self.axis_steer] * self.scale_steer
        elif data.buttons[self.button_change_steering_mode] == 1:
            self.change_steering_mode()
        else:
            cmd.speed = 0.0
            cmd.steering_angle = 0.0

        if not self.is_changing_mode:
            self.cmd_pub.publish(cmd)


def main():
    rclpy.init()
    node = RaphaTeleop()
    rclpy.spin(node)


if __name__ == "__main__":
    main()
