#!/usr/bin/env python3

import rclpy
from rclpy.node import Node

from sensor_msgs.msg import Joy
from ackermann_msgs.msg import AckermannDrive
from rapha_interfaces.srv import SetSteeringMode
from rapha_interfaces.msg import SteeringMode
from std_srvs.srv import Trigger


class RaphaTeleop(Node):
    def __init__(self) -> None:
        super().__init__("rapha_teleop", start_parameter_services=False)

        self.retrieve_parameters()

        self.set_steering_mode_client = self.create_client(
            SetSteeringMode, "controller/set_steering_mode"
        )
        self.calibrate_servos_client = self.create_client(
            Trigger, "controller/calibrate_servos"
        )
        self.panic_client = self.create_client(Trigger, "controller/panic")

        self.current_steering_mode: int = SteeringMode.ACKERMANN
        self.target_steering_mode: int = SteeringMode.ACKERMANN

        self.is_changing_mode = False
        self.is_calibrating_servos = False
        self.is_panicking = False

        self.cmd_pub = self.create_publisher(
            AckermannDrive, "controller/cmd_ackermann", 10
        )
        self.joy_sub = self.create_subscription(Joy, "joy", self.joy_callback, 10)

    def retrieve_parameters(self) -> None:
        self.declare_parameter("acceleration", 2.0)
        self.declare_parameter("steering_angle_velocity", 2.0)
        self.declare_parameter("axis_speed", 1)
        self.declare_parameter("axis_steer", 3)
        self.declare_parameter("button_deadman", 5)
        self.declare_parameter("button_change_steering_mode", 1)
        self.declare_parameter("button_calibrate_servos", 0)
        self.declare_parameter("button_panick", 6)
        self.declare_parameter("scale_speed", 1.0)
        self.declare_parameter("scale_steer", 1.1)

        self.acceleration = (
            self.get_parameter("acceleration").get_parameter_value().double_value
        )
        self.steering_angle_velocity = (
            self.get_parameter("steering_angle_velocity").get_parameter_value().double_value
        )
        self.axis_speed = (
            self.get_parameter("axis_speed").get_parameter_value().integer_value
        )
        self.axis_steer = (
            self.get_parameter("axis_steer").get_parameter_value().integer_value
        )
        self.button_deadman = (
            self.get_parameter("button_deadman").get_parameter_value().integer_value
        )
        self.button_change_steering_mode = (
            self.get_parameter("button_change_steering_mode")
            .get_parameter_value()
            .integer_value
        )
        self.button_calibrate_servos = (
            self.get_parameter("button_calibrate_servos")
            .get_parameter_value()
            .integer_value
        )
        self.button_panick = (
            self.get_parameter("button_panick").get_parameter_value().integer_value
        )
        self.scale_speed = (
            self.get_parameter("scale_speed").get_parameter_value().double_value
        )
        self.scale_steer = (
            self.get_parameter("scale_steer").get_parameter_value().double_value
        )

    def change_steering_mode(self) -> None:
        if self.is_changing_mode:
            return

        if not self.set_steering_mode_client.service_is_ready():
            self.get_logger().error("Failed to change steering mode: Service not ready")
            return

        if self.current_steering_mode == SteeringMode.TURN_IN_PLACE:
            self.target_steering_mode = SteeringMode.ACKERMANN
        else:
            self.target_steering_mode = SteeringMode.TURN_IN_PLACE

        req = SetSteeringMode.Request()
        req.steering_mode.data = self.target_steering_mode
        self.is_changing_mode = True

        future = self.set_steering_mode_client.call_async(req)

        future.add_done_callback(self.set_steering_mode_done_callback)

    def set_steering_mode_done_callback(self, future: rclpy.Future) -> None:
        result: SetSteeringMode.Response = future.result()
        if result.success:
            self.get_logger().error(
                f"Failed to change steering mode: Service response negative: {result.status_message}"
            )
        else:
            self.get_logger().info("Steering mode changed")
            self.current_steering_mode = self.target_steering_mode
        self.is_changing_mode = False

    def calibrate_servos(self) -> None:
        if self.is_calibrating_servos:
            return

        if not self.calibrate_servos_client.service_is_ready():
            self.get_logger().error("Failed to calibrate servos: Service not ready")
            return

        req = Trigger.Request()
        self.is_calibrating_servos = True

        future = self.calibrate_servos_client.call_async(req)

        future.add_done_callback(self.calibrate_servos_done_callback)

    def calibrate_servos_done_callback(self, future: rclpy.Future) -> None:
        result: Trigger.Response = future.result()
        if result.success:
            self.get_logger().error(
                f"Failed to calibrate servos: Service response negative: {result.message}"
            )
        else:
            self.get_logger().info("Servos calibrated")
        self.is_calibrating_servos = False

    def panick(self) -> None:
        if self.is_panicking:
            return

        if not self.panic_client.service_is_ready():
            self.get_logger().error("Failed to panick: Service not ready")
            return

        req = Trigger.Request()
        self.is_panicking = True

        future = self.panic_client.call_async(req)

        future.add_done_callback(self.panick_done_callback)

    def panick_done_callback(self, future: rclpy.Future) -> None:
        result: Trigger.Response = future.result()
        if result.success:
            self.get_logger().error(
                f"Failed to panick: Service response negative: {result.message}"
            )
        else:
            self.get_logger().info("Panicked")
        self.is_panicking = False

    def joy_callback(self, data: Joy) -> None:
        cmd = AckermannDrive()
        cmd.acceleration = self.acceleration
        cmd.steering_angle_velocity = self.steering_angle_velocity

        if data.buttons[self.button_deadman] == 1:
            cmd.speed = data.axes[self.axis_speed] * self.scale_speed
            cmd.steering_angle = data.axes[self.axis_steer] * self.scale_steer
        elif data.buttons[self.button_change_steering_mode] == 1:
            self.change_steering_mode()
        elif data.buttons[self.button_calibrate_servos] == 1:
            self.calibrate_servos()
        elif data.buttons[self.button_panick] == 1:
            self.panick()
        else:
            cmd.speed = 0.0
            cmd.steering_angle = 0.0

        if (
            not self.is_changing_mode
            and not self.is_calibrating_servos
            and not self.is_panicking
        ):
            self.cmd_pub.publish(cmd)


def main():
    rclpy.init()
    node = RaphaTeleop()
    rclpy.spin(node)


if __name__ == "__main__":
    main()
